version: 2
updates:
  - package-ecosystem: bun
    rebase-strategy: "auto"
    directories:
      - "/"
      - "/c"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
