name: Add changeset to Dependabot updates

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  dependabot:
    name: Update Dependabot PR
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@eaebee3ca346aa1c22c48256e5c23faca89edecb
        with:
          token: ${{ secrets.PAT }}
          use-conventional-commits: false
          commit-message: "chore(deps): changeset for dependency update [skip dependabot]"
